AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Distribution for Ghost Blog

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, test, prod]

Resources:
  GhostCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "CloudFront distribution for Ghost Blog - ${Environment}"
        Origins:
          - Id: GhostALBOrigin
            DomainName: !ImportValue
              Fn::Sub: "${Environment}-GhostALBDNS"  # Environment-aware import
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only  # Use HTTP because ALB doesn't support HTTPS
        DefaultCacheBehavior:
          TargetOriginId: GhostALBOrigin
          ViewerProtocolPolicy: redirect-to-https  # Force HTTPS
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          ResponseHeadersPolicyId: !Ref GhostResponseHeadersPolicy
        ViewerCertificate:
          CloudFrontDefaultCertificate: true  # Free AWS-provided certificate
        PriceClass: PriceClass_100  # North America + Europe only (cheapest)
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: GhostBlog

  GhostResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub "GhostSecurityHeadersPolicy-${Environment}"
        Comment: Security headers for Ghost Blog
        SecurityHeadersConfig:
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true
          XSSProtection:
            Protection: true
            ModeBlock: true
            Override: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: GhostBlog

Outputs:
  GhostCloudFrontDomain:
    Description: CloudFront distribution domain name
    Value: !GetAtt GhostCloudFront.DomainName
    Export:
      Name: !Sub "${Environment}-GhostCloudFrontDomain"
