AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Cluster for Ghost Blog

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, test, prod]

Resources:

  GhostEcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${Environment}-ghost-blog-cluster"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-ghost-blog-cluster"
        - Key: Environment
          Value: !Ref Environment

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: AllowSecretsManagerAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:GhostDBCredentials*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DockerHubCredentials*"
        - PolicyName: ECSExecutionPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:GetLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-ecs-execution-role"
        - Key: Environment
          Value: !Ref Environment

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: GhostTaskPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - logs:GetLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - ssm:GetParameter
                Resource: "*"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-ecs-task-role"
        - Key: Environment
          Value: !Ref Environment

  GhostLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${Environment}-ghost-blog"
      RetentionInDays: 14

Outputs:

  ECSClusterName:
    Description: "Name of the ECS Fargate cluster"
    Value: !Ref GhostEcsCluster
    Export:
      Name: !Sub "${Environment}-ECSClusterName"

  ECSExecutionRoleArn:
    Description: "ARN of ECS Execution Role"
    Value: !GetAtt ECSExecutionRole.Arn
    Export:
      Name: !Sub "${Environment}-ECSExecutionRoleArn"

  ECSTaskRoleArn:
    Description: "ARN of ECS Task Role"
    Value: !GetAtt ECSTaskRole.Arn
    Export:
      Name: !Sub "${Environment}-ECSTaskRoleArn"
