AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Cluster for Ghost Blog

Resources:

  # ECS Cluster (Fargate)
  GhostEcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ghost-blog-cluster

  # IAM Role for ECS Fargate task execution
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: AllowSecretsManagerAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:GhostDBCredentials*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DockerHubCredentials*"
        - PolicyName: ECSExecutionPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:GetLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"

  # IAM Role for ECS application container (task role)
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore  # Required for Session Manager (exec access)
      Policies:
        - PolicyName: GhostTaskPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - logs:GetLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - ssm:GetParameter
                Resource: "*"

  # CloudWatch Log Group for ECS service
  GhostLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/ecs/ghost-blog"
      RetentionInDays: 14

Outputs:

  ECSClusterName:
    Description: "Name of the ECS Fargate cluster"
    Value: !Ref GhostEcsCluster
    Export:
      Name: ECSClusterName

  ECSExecutionRoleArn:
    Description: "ARN of ECS Execution Role (used when deploying ECS service)"
    Value: !GetAtt ECSExecutionRole.Arn
    Export:
      Name: ECSExecutionRoleArn

  ECSTaskRoleArn:
    Description: "ARN of ECS Task Role (used by containers)"
    Value: !GetAtt ECSTaskRole.Arn
    Export:
      Name: ECSTaskRoleArn
