AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Service & Task Definition for Ghost Blog (MVP)

Parameters:
  Environment:
    Type: String
    Description: Environment name (e.g., dev, test, prod)
    Default: dev
    AllowedValues: [dev, test, prod]

Resources:
  GhostLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/ghost-blog
      RetentionInDays: 7
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${Environment}-ghost-log-group"
          
  GhostTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${Environment}-ghost-blog-task"
      Cpu: "512"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue:
          Fn::Sub: "${Environment}-ECSExecutionRoleArn"
      TaskRoleArn:
        Fn::ImportValue:
          Fn::Sub: "${Environment}-ECSTaskRoleArn"
      ContainerDefinitions:
        - Name: ghost-container
          Image: ghost:5-alpine
          PortMappings:
            - ContainerPort: 2368
          Environment:
            - Name: url
              Value: !Sub
                - "http://${domain}"
                - domain:
                    Fn::ImportValue:
                      Fn::Sub: "${Environment}-GhostALBDNS"
            - Name: database__client
              Value: mysql
            - Name: database__connection__host
              Value:
                Fn::ImportValue:
                  Fn::Sub: "${Environment}-GhostAuroraEndpoint"
            - Name: database__connection__database
              Value: ghost
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: "/ecs/ghost-blog"
              awslogs-region: "eu-north-1"
              awslogs-stream-prefix: "ecs"
          Secrets:
            - Name: database__connection__user
              ValueFrom: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:GhostDBCredentials:username::"
            - Name: database__connection__password
              ValueFrom: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:GhostDBCredentials:password::"
          RepositoryCredentials:
            CredentialsParameter: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DockerHubCredentials"

  GhostEcsService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub "${Environment}-ghost-blog-service"
      Cluster:
        Fn::ImportValue:
          Fn::Sub: "${Environment}-ECSClusterName"
      TaskDefinition: !Ref GhostTaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      EnableExecuteCommand: true
      HealthCheckGracePeriodSeconds: 60
      DeploymentController:
        Type: ECS
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 200
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue:
                Fn::Sub: "${Environment}-GhostAppSecurityGroupId"
            - Fn::ImportValue:
                Fn::Sub: "${Environment}-GhostSecretsManagerVPCEndpointSGId"
          Subnets:
            - Fn::ImportValue:
                Fn::Sub: "${Environment}-GhostPrivateSubnet1Id"
            - Fn::ImportValue:
                Fn::Sub: "${Environment}-GhostPrivateSubnet2Id"
      LoadBalancers:
        - TargetGroupArn:
            Fn::ImportValue:
              Fn::Sub: "${Environment}-GhostTargetGroupArn"
          ContainerName: ghost-container
          ContainerPort: 2368

Outputs:
  ECSServiceName:
    Description: "Name of the ECS service"
    Value: !Ref GhostEcsService
    Export:
      Name: !Sub "${Environment}-ECSServiceName"
