AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC and networking resources for ECS Fargate and Aurora RDS"

Resources:

  GhostVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: ghost-vpc

  # Internet Gateway attached to VPC because Fargate needs to download Docker images
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref GhostVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GhostVPC
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: ghost-public-subnet-1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GhostVPC
      CidrBlock: "10.0.2.0/24"
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: ghost-public-subnet-2

  # Security groups
  # App Security Group for ECS tasks
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "App Security Group for ECS tasks (Ghost HTTP & DB connections)"
      VpcId: !Ref GhostVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2368
          ToPort: 2368
          CidrIp: 0.0.0.0/0  # Ghost blog HTTP open to everyone. TODO: restrict!

  # DB Security Group (only accepts traffic from app SG)
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Aurora MySQL Security Group (allows access from App SG only)"
      VpcId: !Ref GhostVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref AppSecurityGroup

  # Security Group for ALB
  GhostALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for ALB"
      VpcId: !Ref GhostVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # TODO: restrict this later


  # Route table for public subnets (internet-bound traffic)
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref GhostVPC
      Tags:
        - Key: Name
          Value: ghost-public-route-table

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachInternetGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"  # TODO: review this later
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # Private subnets for RDS
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GhostVPC
      CidrBlock: "10.0.3.0/24"
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: ghost-private-subnet-1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GhostVPC
      CidrBlock: "10.0.4.0/24"
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: ghost-private-subnet-2

  # SG for VPC Endpoint to access Secrets Manager from ECS tasks
  SecretsManagerVPCEndpointSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "SG for Secrets Manager VPC Endpoint"
      VpcId: !Ref GhostVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref AppSecurityGroup
      Tags:
        - Key: Name
          Value: ghost-secrets-manager-vpc-sg

  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref GhostVPC
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.secretsmanager"
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      SecurityGroupIds:
        - !Ref SecretsManagerVPCEndpointSG
      PrivateDnsEnabled: true

  # NAT Gateway for ECS Fargate to download Docker images
  GhostNATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt GhostEIP.AllocationId
      SubnetId: !Ref PublicSubnet1

  # Elastic IP for NAT Gateway
  GhostEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  # Private route table with NAT
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref GhostVPC
      Tags:
        - Key: Name
          Value: ghost-private-route-table

  PrivateRoute:
    Type: AWS::EC2::Route
    DependsOn: GhostNATGateway
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref GhostNATGateway

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

Outputs:

  SecretsManagerVPCEndpointSGId:
    Description: "SG ID for Secrets Manager VPC Endpoint"
    Value: !Ref SecretsManagerVPCEndpointSG
    Export:
      Name: GhostSecretsManagerVPCEndpointSGId

  VPCId:
    Description: "VPC ID"
    Value: !Ref GhostVPC
    Export:
      Name: GhostVPCId

  PublicSubnet1Id:
    Description: "Public Subnet 1"
    Value: !Ref PublicSubnet1
    Export:
      Name: GhostPublicSubnet1Id

  PublicSubnet2Id:
    Description: "Public Subnet 2"
    Value: !Ref PublicSubnet2
    Export:
      Name: GhostPublicSubnet2Id

  PrivateSubnet1Id:
    Description: "Private Subnet 1"
    Value: !Ref PrivateSubnet1
    Export:
      Name: GhostPrivateSubnet1Id

  PrivateSubnet2Id:
    Description: "Private Subnet 2"
    Value: !Ref PrivateSubnet2
    Export:
      Name: GhostPrivateSubnet2Id

  GhostALBSecurityGroupId:
    Description: "SG ID for ALB"
    Value: !Ref GhostALBSecurityGroup
    Export:
      Name: GhostALBSecurityGroupId

  AppSecurityGroupId:
    Description: "App Security Group ID"
    Value: !Ref AppSecurityGroup
    Export:
      Name: GhostAppSecurityGroupId

  DBSecurityGroupId:
    Description: "Aurora DB Security Group ID"
    Value: !Ref DBSecurityGroup
    Export:
      Name: GhostDBSecurityGroupId
