AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora MySQL RDS Cluster for Ghost Blog

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, test, prod]

Resources:

  # Aurora Subnet Group (required to deploy across multiple Availability Zones)
  GhostDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub "${Environment} Aurora Subnet Group"
      SubnetIds:
        - !ImportValue "${Environment}-GhostPrivateSubnet1Id"
        - !ImportValue "${Environment}-GhostPrivateSubnet2Id"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-ghost-db-subnet-group"
        - Key: Environment
          Value: !Ref Environment

  # Aurora DB Cluster (stores the actual data)
  GhostAuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineVersion: "8.0.mysql_aurora.3.05.2"
      MasterUsername: !Sub "{{resolve:secretsmanager:GhostDBCredentials:SecretString:username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:GhostDBCredentials:SecretString:password}}"
      DBSubnetGroupName: !Ref GhostDBSubnetGroup
      VpcSecurityGroupIds:
        - !ImportValue "${Environment}-GhostDBSecurityGroupId"
      BackupRetentionPeriod: 1  # Retain snapshots for 1 day (minimal cost)
      PreferredBackupWindow: "03:00-04:00"
      StorageEncrypted: true
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-ghost-db-cluster"
        - Key: Environment
          Value: !Ref Environment

  # Aurora DB Instance (smallest and cheapest for MVP)
  GhostAuroraInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Ref GhostAuroraCluster
      DBInstanceClass: db.t4g.medium
      Engine: aurora-mysql
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-ghost-db-instance"
        - Key: Environment
          Value: !Ref Environment

Outputs:

  AuroraEndpoint:
    Description: "Aurora DB endpoint used by ECS app"
    Value: !GetAtt GhostAuroraCluster.Endpoint.Address
    Export:
      Name: !Sub "${Environment}-GhostAuroraEndpoint"
